---
version: "2.4"

services:
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: "openmensa"
      POSTGRES_PASSWORD: "openmensa"
      POSTGRES_DB: "openmensa"
    volumes:
    - ./volume/pg_data:/var/lib/postgresql/data

  openmensa:
    image: ghcr.io/openmensa/openmensa:latest
    restart: always
    environment:
      DATABASE_URL: "postgresql://openmensa:openmensa@postgres/openmensa"
    volumes:
    - ./volume/www:/mnt/openmensa-www
    # ports:
    # - "3000:3000" # TODO: temporary?
    depends_on:
    - postgres

  nginx:
    image: nginx:1.20-alpine
    restart: always
    volumes:
    - ./volume/www:/mnt/openmensa-www
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - "8080:8080"
    depends_on:
    - openmensa
