---
name: CI

on: [push, pull_request]

jobs:
  test:
    name: rspec
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      TZ: Europe/Berlin
      DATABASE_URL: postgresql://postgres:secret@localhost:5432

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Setup
        run: |
          bundle exec rake db:create:all db:setup
          sudo bash -c "echo 127.0.1.2 openmensa.org >> /etc/hosts"
      - run: bundle exec rspec spec --tag ~type:feature --format doc
      - run: bundle exec rspec spec --tag type:feature --format doc


  rubocop:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle exec rubocop --color --parallel --fail-level E


  docker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: openmensa/openmensa:latest


  actionlint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Check workflow files
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint
